### ISSUE TITLE
Cannot invoke "net.citizensnpcs.api.npc.NPC.getEntity()" because "this.npc" is null

### ISSUE THREAD

**Issue by davidleebooth** [yro7/LLM-craft#1]
Hi there, I am really interested in giving this plugin a go on my server, I can speak to agents via admin commands, I have the models set to NPC's with the appropriate citizen IDs but I am unable to communicate with them through the chat or interact through the game, If this helps I am getting this in the console:

`30.09 06:08:39 [Server] ERROR Could not pass event AsyncPlayerChatEvent to LLM-craft v1.0-SNAPSHOT
30.09 06:08:39 [Server] INFO java.lang.NullPointerException: Cannot invoke "net.citizensnpcs.api.npc.NPC.getEntity()" because "this.npc" is null
30.09 06:08:39 [Server] INFO at LLMCraft-0.3.1.jar/fr.yro.llmcraft.Citizens.TalkingCitizen.getLocation(TalkingCitizen.java:145) ~[LLMCraft-0.3.1.jar:?]
30.09 06:08:39 [Server] INFO at LLMCraft-0.3.1.jar/fr.yro.llmcraft.Citizens.NPCListener.onMessage(NPCListener.java:30) ~[LLMCraft-0.3.1.jar:?]
30.09 06:08:39 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor315.execute(Unknown Source) ~[?:?]
30.09 06:08:39 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
30.09 06:08:39 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
30.09 06:08:39 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
30.09 06:08:39 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2406) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2522) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$9(ServerGamePacketListenerImpl.java:2178) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[paper-1.21.1.jar:1.21.1-85-c5a1066]
30.09 06:08:39 [Server] INFO at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
30.09 06:08:39 [Server] INFO at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
30.09 06:08:39 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
30.09 06:08:39 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
30.09 06:08:39 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by yro7** [comment]
Hello,

Thanks your for the report and for giving the plug-in a try.

For now, you can fix this by running /llmcraft reload after your server has finished starting.
I'm fixing the issue as soon as possible and I'll let you know when it's done !

**Comment by davidleebooth** [comment]
...and we are cooking!
Thank you very much for the workaround. I will for sure be putting this plugin to work on my server, and likely have some suggestions and QOL feature requests to consider if you happen to be road-mapping anything :)

**Comment by yro7** [comment]
Fixed in the v0.3.2 release, thanks again! Don't hesitate to add a review on spigot also :)
